#!/usr/bin/env bash
# One-time (idempotent) staging-VPS bootstrap for Oxford HIS (ADR-0064/ADR-0070).
# Run ON the VPS as root. Safe to re-run: every step checks before it acts.
#
# The deploy workflow invokes this automatically when /opt/oxford-his is missing,
# so adding the three repo secrets (VPS_HOST/VPS_USER/VPS_SSH_KEY) is the ONLY
# manual setup step — see docs/CICD_SETUP.md.
#
# ISOLATION GUARANTEE: this script only touches its own stack —
#   /opt/oxford-his, /etc/oxford-his, oxford-his-api.service, the
#   oxford_staging database, /var/backups/oxford-his, and its own cron line.
# It never reads, writes, or restarts anything under /opt/oxmedkw or the
# om-software nginx sites (in daily clinical use).
#
# RESIDENCY (ADR-0007): this VPS is STAGING / SYNTHETIC DATA ONLY.
set -euo pipefail

REPO_URL=${REPO_URL:-https://github.com/psn-github/emr.git}
APP_DIR=/opt/oxford-his
ENV_DIR=/etc/oxford-his
ENV_FILE=$ENV_DIR/api.env
DB_NAME=oxford_staging
DB_USER=oxford
PORT=8060

log() { echo "bootstrap: $*"; }

[ "$(id -u)" = "0" ] || { echo "bootstrap: must run as root"; exit 1; }

# 1. Node 20+ (om-software's tools may already provide it; install only if absent/old).
need_node=1
if command -v node >/dev/null 2>&1; then
  major=$(node -v | sed 's/^v\([0-9]*\).*/\1/')
  [ "$major" -ge 20 ] && need_node=0
fi
if [ "$need_node" = "1" ]; then
  log "installing Node 20 (NodeSource)"
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash - >/dev/null
  DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs >/dev/null
fi
log "node $(node -v)"

# 2. pnpm via corepack, pinned to the repo's packageManager version.
if ! command -v pnpm >/dev/null 2>&1; then
  corepack enable >/dev/null 2>&1 || npm install -g corepack >/dev/null
  corepack prepare pnpm@9.15.9 --activate >/dev/null
fi
log "pnpm $(pnpm --version)"

# 3. PostgreSQL (skip if a server is already running on :5432).
if ! pg_isready -q -h 127.0.0.1 -p 5432 2>/dev/null; then
  log "installing PostgreSQL"
  DEBIAN_FRONTEND=noninteractive apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql >/dev/null
  systemctl enable --now postgresql
fi

# 4. Role + database (idempotent; password generated once into the env file).
mkdir -p "$ENV_DIR"
if [ ! -f "$ENV_FILE" ]; then
  DB_PASS=$(openssl rand -hex 24)
  cat > "$ENV_FILE" <<EOF
# Oxford HIS staging API environment (generated by vps-bootstrap.sh).
# STAGING ONLY (ADR-0007): synthetic data; never real PHI; never NODE_ENV=production.
DATABASE_URL=postgresql://$DB_USER:$DB_PASS@127.0.0.1:5432/$DB_NAME
PORT=$PORT
NODE_ENV=staging
DOCUMENT_STORE_DIR=/opt/oxford-his-data/documents
EOF
  chmod 600 "$ENV_FILE"
  log "wrote $ENV_FILE"
fi
DB_PASS=$(grep '^DATABASE_URL=' "$ENV_FILE" | sed 's|.*//[^:]*:\([^@]*\)@.*|\1|')
su postgres -c "psql -tc \"SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'\"" | grep -q 1 \
  || su postgres -c "psql -c \"CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASS'\""
su postgres -c "psql -tc \"SELECT 1 FROM pg_database WHERE datname='$DB_NAME'\"" | grep -q 1 \
  || su postgres -c "createdb -O $DB_USER $DB_NAME"
log "database $DB_NAME ready"

# 5. App checkout (the DB and documents live OUTSIDE this dir — PATIENT-DATA rule).
if [ ! -d "$APP_DIR/.git" ]; then
  git clone "$REPO_URL" "$APP_DIR"
  log "cloned $REPO_URL"
fi
mkdir -p /opt/oxford-his-data/documents /var/backups/oxford-his

# 6. systemd unit (from the repo template; root-run staging service kept simple —
#    the unit file's oxfordhis user is used when it exists).
if ! id oxfordhis >/dev/null 2>&1; then
  useradd --system --home "$APP_DIR" --shell /usr/sbin/nologin oxfordhis || true
fi
chown -R oxfordhis:oxfordhis /opt/oxford-his-data
if [ ! -f /etc/systemd/system/oxford-his-api.service ]; then
  cp "$APP_DIR/deploy/oxford-his-api.service" /etc/systemd/system/
  systemctl daemon-reload
  systemctl enable oxford-his-api >/dev/null
  log "installed oxford-his-api.service"
fi

# 7. Nightly backup cron (own marker line; never rewrites other cron entries).
if ! crontab -l 2>/dev/null | grep -q oxford-his; then
  (crontab -l 2>/dev/null; echo "15 2 * * * $APP_DIR/scripts/backup-staging-db.sh # oxford-his") | crontab -
  log "installed nightly backup cron"
fi

log "bootstrap complete — deploy-api will build, migrate, and start the service"
